language: c

matrix:
 include:
  - compiler: clang
    env: CONFIG_OPTS="-Dusemallocwrap=no"
  - compiler: gcc
    env: CONFIG_OPTS="-Dusemallocwrap=no"
  - compiler: gcc
    env: CONFIG_OPTS="-Dusemallocwrap=no -Dusethreads"
  - compiler: gcc
    env: CONFIG_OPTS="-Dusemallocwrap=no -Duselongdouble"
  - compiler: gcc
    env: CONFIG_OPTS="-Duseshrplib"

script:
 - ./configure.gnu --prefix=/opt/bleadperl -Dusedevel $CONFIG_OPTS
 - make -j4 all
# Remove .travis.yml, as porting/manifest.t fails on extra files
# (Hopefully .travis.yml is not needed at this point anymore!)
 - git rm .travis.yml
 - env TEST_JOBS=4 make test_harness

branches:
 except:
  - /appveyor/

## Because of https://rt.perl.org/Ticket/Display.html?id=130143
#sudo: false
sudo: true
